<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>adf4b8e3-435d-493c-b6f7-fc08adf06ecf</testSuiteGuid>
   <testCaseLink>
      <guid>1e6212d3-da20-4308-9e02-dc4f35e32ff9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7fd6de5e-4d7b-495a-bc47-36ae272e9331</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/testdatasoap</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7fd6de5e-4d7b-495a-bc47-36ae272e9331</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>countryISOCode</value>
         <variableId>8cd2bb22-603b-481e-a65e-fc806b7e229e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7fd6de5e-4d7b-495a-bc47-36ae272e9331</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Capital</value>
         <variableId>3e1da71a-0bc1-4773-ac5f-93203dd1eb63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7fd6de5e-4d7b-495a-bc47-36ae272e9331</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>currency1</value>
         <variableId>67b47a18-889b-4cc8-a2d8-fca0b0c5fe2a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
